//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlankBlazorApp.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlankBlazorApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на importScripts(&quot;https://www.gstatic.com/firebasejs/12.11.0/firebase-app-compat.js&quot;);
        ///importScripts(&quot;https://www.gstatic.com/firebasejs/12.11.0/firebase-messaging-compat.js&quot;);
        ///importScripts(&quot;https://www.gstatic.com/firebasejs/12.11.0/firebase-analytics-compat.js&quot;);
        ///
        ///// Initialize Firebase using the global firebase object exposed by compat libraries
        ///const firebaseConfig = {
        ///    apiKey: &quot;AIzaSyCPlUkq609DA2CpFZsP88v-FIfFBU6uGRI&quot;,
        ///    authDomain: &quot;evident-ethos-230204.firebaseapp.com&quot;,
        ///    databaseURL: &quot;h [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string firebase_messaging_sw {
            get {
                return ResourceManager.GetString("firebase-messaging-sw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на import { initializeApp } from &quot;https://www.gstatic.com/firebasejs/12.11.0/firebase-app.js&quot;;
        ///import { getAnalytics, logEvent } from &quot;https://www.gstatic.com/firebasejs/12.11.0/firebase-analytics.js&quot;;
        ///import { getMessaging, getToken } from &quot;https://www.gstatic.com/firebasejs/12.11.0/firebase-messaging.js&quot;;
        ///
        ///// Initialize Firebase using the global firebase object exposed by compat libraries
        ///const firebaseConfig = {
        ///    apiKey: &quot;AIzaSyCPlUkq609DA2CpFZsP88v-FIfFBU6uGRI&quot;,
        ///    authDomain: &quot;evident-ethos-230 [остаток строки не уместился]&quot;;.
        /// </summary>
        public static string FirebaseSDK {
            get {
                return ResourceManager.GetString("FirebaseSDK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] noimage_simple {
            get {
                object obj = ResourceManager.GetObject("noimage-simple", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        public static byte[] unauthorizedimage {
            get {
                object obj = ResourceManager.GetObject("unauthorizedimage", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
