$foldersList = @(".\BlankBlazorApp\BlankBlazorApp\bin\",
".\BlankBlazorApp\BlankBlazorApp.Client\bin\",
".\BlankCRM.AppHost\bin\",
".\BlankCRM.ServiceDefaults\bin\",
".\BlazorLib\bin\",
".\BlazorServerLib\bin\",
".\CodegeneratorLib\bin\",
".\DBContextLibs\DbLayerLib\bin\",
".\DBContextLibs\DbMySQLLib\bin\",
".\DBContextLibs\DbPostgreLib\bin\",
".\DBContextLibs\DbSqliteLib\bin\",
".\IdentityLib\bin\",
".\micro-services\ApiRestService\bin\",
".\micro-services\BankService\bin\",
".\micro-services\CommerceService\bin\",
".\micro-services\ConstructorService\bin\",
".\micro-services\FilesIndexingService\bin\",
".\micro-services\RealtimeService\bin\",
".\micro-services\HelpDeskService\bin\",
".\micro-services\IdentityService\bin\",
".\micro-services\KladrService\bin\",
".\micro-services\LdapService\bin\",
".\micro-services\StorageService\bin\",
".\micro-services\TelegramBotService\bin\",
".\RemoteCallLib\MQTTCallLib\bin\",
".\RemoteCallLib\RabbitMQ\bin\",
".\ServerLib\bin\",
".\SharedLib\bin\",
".\SharedLibStandard21\bin\",
".\ToolsApp\ToolsMauiApp\bin\",
".\ToolsApp\ToolsMauiAppMigration\bin\",
".\ToolsApp\ToolsMauiLib\bin\",
".\BlankBlazorApp\BlankBlazorApp\obj\",
".\BlankBlazorApp\BlankBlazorApp.Client\obj\",
".\BlankCRM.AppHost\obj\",
".\BlankCRM.ServiceDefaults\obj\",
".\BlazorLib\obj\",
".\BlazorServerLib\obj\",
".\CodegeneratorLib\obj\",
".\DBContextLibs\DbLayerLib\obj\",
".\DBContextLibs\DbMySQLLib\obj\",
".\DBContextLibs\DbPostgreLib\obj\",
".\DBContextLibs\DbSqliteLib\obj\",
".\IdentityLib\obj\",
".\micro-services\ApiRestService\obj\",
".\micro-services\BankService\obj\",
".\micro-services\CommerceService\obj\",
".\micro-services\ConstructorService\obj\",
".\micro-services\RealtimeService\obj\",
".\micro-services\HelpDeskService\obj\",
".\micro-services\IdentityService\obj\",
".\micro-services\KladrService\obj\",
".\micro-services\LdapService\obj\",
".\micro-services\StorageService\obj\",
".\micro-services\TelegramBotService\obj\",
".\RemoteCallLib\MQTTCallLib\obj\",
".\RemoteCallLib\RabbitMQ\obj\",
".\ServerLib\obj\",
".\SharedLib\obj\",
".\SharedLibStandard21\obj\",
".\ToolsApp\ToolsMauiApp\obj\",
".\ToolsApp\ToolsMauiAppMigration\obj\",
".\ToolsApp\ToolsMauiLib\obj\")

# Loop through each file in the array
foreach ($folderPath in $foldersList) {
    if (Test-Path -Path $folderPath) {
        Write-Host "Folder exists. Deleting..."
        Remove-Item -Path $folderPath -Recurse -Force
        Write-Host "Folder deleted."
    } else {
        Write-Host "Folder does not exist. No action needed."
    }
}