////////////////////////////////////////////////
// © https://github.com/badhitman - @FakeGov
////////////////////////////////////////////////

using Transmission.Receives.commerce;
using SharedLib;

namespace CommerceService;

/// <summary>
/// MQ listen
/// </summary>
public static class RegisterMqListenerExtension
{
    /// <summary>
    /// RegisterMqListeners
    /// </summary>
    public static IServiceCollection CommerceRegisterMqListeners(this IServiceCollection services)
    {
        return services
            .RegisterListenerRabbitMQ<UpdateWalletTypeReceive, TAuthRequestStandardModel<WalletRetailTypeModelDB>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<ToggleWalletTypeDisabledForPaymentTypeReceive, TAuthRequestStandardModel<ToggleWalletTypeDisabledForPaymentTypeRequestModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<UpdateWalletReceive, WalletRetailModelDB, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<UpdateRowOfDeliveryDocumentReceive, TAuthRequestStandardModel<RowOfDeliveryRetailDocumentModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<UpdatePaymentDocumentReceive, TAuthRequestStandardModel<PaymentRetailDocumentModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<UpdatePaymentOrderLinkDocumentReceive, TAuthRequestStandardModel<PaymentOrderRetailLinkModelDB>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<UpdateDeliveryStatusDocumentReceive, TAuthRequestStandardModel<DeliveryStatusRetailDocumentModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<UpdateDeliveryDocumentReceive, TAuthRequestStandardModel<DeliveryDocumentRetailModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<UpdateConversionDocumentReceive, TAuthRequestStandardModel<WalletConversionRetailDocumentModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<DeleteConversionOrderLinkDocumentReceive, TAuthRequestStandardModel<OrderConversionModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<DeleteToggleConversionReceive, TAuthRequestStandardModel<DeleteToggleConversionRequestModel>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<UpdateConversionOrderLinkDocumentReceive, TAuthRequestStandardModel<OrderConversionAmountModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<StatusesOrdersAttendancesChangeByHelpDeskDocumentIdReceive, TAuthRequestStandardModel<StatusChangeRequestModel>, TResponseModel<List<RecordsAttendanceModelDB>>>()
            .RegisterListenerRabbitMQ<SelectWalletsTypesReceive, TPaginationRequestStandardModel<SelectWalletsRetailsTypesRequestModel>, TPaginationResponseStandardModel<WalletRetailTypeViewModel>>()
            .RegisterListenerRabbitMQ<SelectWalletsReceive, TPaginationRequestStandardModel<SelectWalletsRetailsRequestModel>, TPaginationResponseStandardModel<WalletRetailModelDB>>()
            .RegisterListenerRabbitMQ<SelectRowOfDeliveryDocumentsReceive, TPaginationRequestStandardModel<SelectRowsOfDeliveriesRetailDocumentsRequestModel>, TPaginationResponseStandardModel<RowOfDeliveryRetailDocumentModelDB>>()
            .RegisterListenerRabbitMQ<SelectPaymentsDocumentsReceive, TPaginationRequestStandardModel<SelectPaymentsRetailOrdersDocumentsRequestModel>, TPaginationResponseStandardModel<PaymentRetailDocumentModelDB>>()
            .RegisterListenerRabbitMQ<SelectDeliveryStatusesDocumentsReceive, TPaginationRequestStandardModel<SelectDeliveryStatusesRetailDocumentsRequestModel>, TPaginationResponseStandardModel<DeliveryStatusRetailDocumentModelDB>>()
            .RegisterListenerRabbitMQ<SelectDeliveryDocumentsReceive, TPaginationRequestStandardModel<SelectDeliveryDocumentsRetailRequestModel>, TPaginationResponseStandardModel<DeliveryDocumentRetailModelDB>>()
            .RegisterListenerRabbitMQ<SelectConversionsDocumentsReceive, TPaginationRequestStandardModel<SelectWalletsRetailsConversionDocumentsRequestModel>, TPaginationResponseStandardModel<WalletConversionRetailDocumentModelDB>>()
            .RegisterListenerRabbitMQ<SelectConversionsOrdersDocumentsLinksReceive, TPaginationRequestStandardModel<SelectConversionsOrdersLinksRetailDocumentsRequestModel>, TPaginationResponseStandardModel<ConversionOrderRetailLinkModelDB>>()
            .RegisterListenerRabbitMQ<ConversionsOrdersDocumentsLinksReadRetailReceive, int[], TResponseModel<ConversionOrderRetailLinkModelDB[]>>()
            .RegisterListenerRabbitMQ<CreateWalletTypeReceive, TAuthRequestStandardModel<WalletRetailTypeModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<CreateWalletReceive, WalletRetailModelDB, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<CreateRowOfDeliveryDocumentReceive, TAuthRequestStandardModel<RowOfDeliveryRetailDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<CreatePaymentDocumentReceive, TAuthRequestStandardModel<CreatePaymentRetailDocumentRequestModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<FinancialsReportRetailReceive, TPaginationRequestStandardModel<SelectPaymentsRetailReportRequestModel>, TPaginationResponseStandardModel<WalletRetailReportRowModel>>()
            .RegisterListenerRabbitMQ<GetMainReportRetailReceive, MainReportRequestModel, MainReportResponseModel>()
            .RegisterListenerRabbitMQ<AboutPeriodRetailReceive, object, PeriodBaseModel>()
            .RegisterListenerRabbitMQ<OffersOfOrdersReportRetailReceive, TPaginationRequestStandardModel<SelectOffersOfOrdersRetailReportRequestModel>, TPaginationResponseStandardModel<OffersRetailReportRowModel>>()
            .RegisterListenerRabbitMQ<OffersOfDeliveriesReportRetailReceive, TPaginationRequestStandardModel<SelectOffersOfDeliveriesRetailReportRequestModel>, TPaginationResponseStandardModel<OffersRetailReportRowModel>>()
            .RegisterListenerRabbitMQ<SelectRowsDocumentsForMainReportRetailReceive, TPaginationRequestStandardModel<MainReportRequestModel>, TPaginationResponseStandardModel<DocumentRetailModelDB>>()
            .RegisterListenerRabbitMQ<DeletePaymentOrderLinkDocumentReceive, TAuthRequestStandardModel<OrderPaymentModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<CreatePaymentOrderLinkDocumentReceive, TAuthRequestStandardModel<PaymentOrderRetailLinkModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<GetPaymentsDocumentsReceive, GetPaymentsRetailOrdersDocumentsRequestModel, TResponseModel<PaymentRetailDocumentModelDB[]>>()
            .RegisterListenerRabbitMQ<CreateDeliveryStatusDocumentReceive, TAuthRequestStandardModel<DeliveryStatusRetailDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<CreateDeliveryDocumentReceive, TAuthRequestStandardModel<CreateDeliveryDocumentRetailRequestModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<GetDeliveriesJournalFileReceive, SelectDeliveryDocumentsRetailRequestModel, FileAttachModel>()
            .RegisterListenerRabbitMQ<DeleteRowOfDeliveryDocumentReceive, TAuthRequestStandardModel<DeleteRowOfDeliveryDocumentRequestModel>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<TotalWeightOrdersLinksDocumentsReceive, TotalWeightDeliveriesOrdersLinksDocumentsRequestModel, TResponseModel<decimal>>()
            .RegisterListenerRabbitMQ<DeleteDeliveryStatusDocumentReceive, TAuthRequestStandardModel<DeleteDeliveryStatusDocumentRequestModel>?, DeleteDeliveryStatusDocumentResponseModel>()
            .RegisterListenerRabbitMQ<GetDeliveryDocumentsReceive, GetDeliveryDocumentsRetailRequestModel, TResponseModel<DeliveryDocumentRetailModelDB[]>>()
            .RegisterListenerRabbitMQ<CreateConversionDocumentReceive, TAuthRequestStandardModel<CreateWalletConversionRetailDocumentRequestModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<GetSumConversionsOrdersAmountsReceive, GetSumConversionsOrdersAmountsRequestModel, TResponseModel<decimal>>()
            .RegisterListenerRabbitMQ<CreateConversionOrderLinkDocumentReceive, TAuthRequestStandardModel<OrderConversionAmountModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<GetConversionsDocumentsReceive, ReadWalletsRetailsConversionDocumentsRequestModel, TResponseModel<WalletConversionRetailDocumentModelDB[]>>()
            .RegisterListenerRabbitMQ<WalletsTypesGetReceive, int[], TResponseModel<WalletRetailTypeViewModel[]>>()
            .RegisterListenerRabbitMQ<SelectRetailDocumentsReceive, TPaginationRequestStandardModel<SelectRetailDocumentsRequestModel>, TPaginationResponseStandardModel<DocumentRetailModelDB>>()
            .RegisterListenerRabbitMQ<SelectPaymentsOrdersDocumentsLinksReceive, TPaginationRequestStandardModel<SelectPaymentsOrdersLinksRetailDocumentsRequestModel>, TPaginationResponseStandardModel<PaymentOrderRetailLinkModelDB>>()
            .RegisterListenerRabbitMQ<PaymentsOrdersDocumentsLinksGetReceive, int[], TResponseModel<PaymentOrderRetailLinkModelDB[]>>()
            .RegisterListenerRabbitMQ<SelectOrderDocumentStatusesReceive, TPaginationRequestStandardModel<SelectOrderStatusesRetailDocumentsRequestModel>, TPaginationResponseStandardModel<OrderStatusRetailDocumentModelDB>>()
            .RegisterListenerRabbitMQ<CreateRetailDocumentReceive, TAuthRequestStandardModel<CreateDocumentRetailRequestModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<CreateDeliveryOrderLinkDocumentReceive, TAuthRequestStandardModel<RetailOrderDeliveryLinkModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<CreateOrderStatusDocumentReceive, TAuthRequestStandardModel<OrderStatusRetailDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<DeleteDeliveryOrderLinkDocumentReceive, TAuthRequestStandardModel<OrderDeliveryModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<DeleteRowRetailDocumentReceive, TAuthRequestStandardModel<DeleteRowRetailDocumentRequestModel>, DeleteRowRetailDocumentResponseModel>()
            .RegisterListenerRabbitMQ<DeleteOrderStatusDocumentReceive, TAuthRequestStandardModel<DeleteOrderStatusDocumentRequestModel>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<UpdateDeliveryOrderLinkDocumentReceive, TAuthRequestStandardModel<RetailOrderDeliveryLinkModelDB>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<SelectDeliveriesOrdersLinksDocumentsReceive, TPaginationRequestStandardModel<SelectDeliveriesOrdersLinksRetailDocumentsRequestModel>, TPaginationResponseStandardModel<RetailOrderDeliveryLinkModelDB>>()
            .RegisterListenerRabbitMQ<DeliveriesOrdersLinksDocumentsReadReceive, int[], TResponseModel<RetailOrderDeliveryLinkModelDB[]>>()
            .RegisterListenerRabbitMQ<UpdateRetailDocumentReceive, TAuthRequestStandardModel<DocumentRetailModelDB>, TResponseModel<Guid>>()
            .RegisterListenerRabbitMQ<UpdateOrderStatusDocumentReceive, TAuthRequestStandardModel<OrderStatusRetailDocumentModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<RetailDocumentsGetReceive, RetailDocumentsGetRequestModel, TResponseModel<DocumentRetailModelDB[]>>()
            .RegisterListenerRabbitMQ<CreateRowRetailDocumentReceive, TAuthRequestStandardModel<RowOfRetailOrderDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<SelectRowsRetailDocumentsReceive, TPaginationRequestStandardModel<SelectRowsRetailDocumentsRequestModel>, TPaginationResponseStandardModel<RowOfRetailOrderDocumentModelDB>>()
            .RegisterListenerRabbitMQ<UpdateRowRetailDocumentReceive, TAuthRequestStandardModel<RowOfRetailOrderDocumentModelDB>, TResponseModel<Guid?>>()
            .RegisterListenerRabbitMQ<OrganizationSetLegalReceive, TAuthRequestStandardModel<OrganizationLegalModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<OrganizationUpdateOrCreateReceive, TAuthRequestStandardModel<OrganizationModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<OrganizationsSelectReceive, TPaginationRequestAuthModel<OrganizationsSelectRequestModel>, TPaginationResponseStandardModel<OrganizationModelDB>>()
            .RegisterListenerRabbitMQ<OfficeOrganizationUpdateOrCreateReceive, TAuthRequestStandardModel<AddressOrganizationBaseModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<OfficeOrganizationDeleteReceive, TAuthRequestStandardModel<OfficeOrganizationDeleteRequestModel>, TResponseModel<OfficeOrganizationModelDB>>()
            .RegisterListenerRabbitMQ<RecordsAttendancesSelectReceive, TPaginationRequestAuthModel<RecordsAttendancesRequestModel>, TPaginationResponseStandardModel<RecordsAttendanceModelDB>>()
            .RegisterListenerRabbitMQ<NomenclatureUpdateOrCreateReceive, NomenclatureModelDB, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<RubricsForNomenclaturesSetReceive, TAuthRequestStandardModel<RubricsSetModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<OrdersByIssuesGetReceive, OrdersByIssuesSelectRequestModel, TResponseModel<OrderDocumentModelDB[]>>()
            .RegisterListenerRabbitMQ<UploadOffersReceive, List<NomenclatureScopeModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<AttendanceRecordsDeleteReceive, TAuthRequestStandardModel<int[]>, TResponseModel<RecordsAttendanceModelDB[]>>()
            .RegisterListenerRabbitMQ<OrganizationUserUpdateOrCreateReceive, TAuthRequestStandardModel<UserOrganizationModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<UsersOrganizationsReadReceive, int[], TResponseModel<UserOrganizationModelDB[]>>()
            .RegisterListenerRabbitMQ<UsersOrganizationsSelectReceive, TPaginationRequestAuthModel<UsersOrganizationsStatusesRequestModel>, TResponseModel<TPaginationResponseStandardModel<UserOrganizationModelDB>>>()
            .RegisterListenerRabbitMQ<BankDetailsForOrganizationDeleteReceive, TAuthRequestStandardModel<BankDetailsForOrganizationDeleteRequestModel>, TResponseModel<BankDetailsModelDB>>()
            .RegisterListenerRabbitMQ<BankDetailsUpdateOrCreateReceive, TAuthRequestStandardModel<BankDetailsModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<WeeklyScheduleCreateOrUpdateReceive, TAuthRequestStandardModel<WeeklyScheduleModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<WeeklySchedulesSelectReceive, TPaginationRequestStandardModel<WorkSchedulesSelectRequestModel>, TPaginationResponseStandardModel<WeeklyScheduleModelDB>>()
            .RegisterListenerRabbitMQ<WeeklySchedulesReadReceive, int[], List<WeeklyScheduleModelDB>>()
            .RegisterListenerRabbitMQ<CalendarScheduleUpdateOrCreateReceive, TAuthRequestStandardModel<CalendarScheduleModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<CalendarsSchedulesSelectReceive, TAuthRequestStandardModel<TPaginationRequestStandardModel<WorkScheduleCalendarsSelectRequestModel>>, TResponseModel<TPaginationResponseStandardModel<CalendarScheduleModelDB>>>()
            .RegisterListenerRabbitMQ<CalendarsSchedulesReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<List<CalendarScheduleModelDB>>>()
            .RegisterListenerRabbitMQ<PriceFullFileGetExcelReceive, object, FileAttachModel>()
            .RegisterListenerRabbitMQ<PriceFullFileGetJsonReceive, object, FileAttachModel>()
            .RegisterListenerRabbitMQ<OrderReportGetReceive, TAuthRequestStandardModel<int>, TResponseModel<FileAttachModel>>()
            .RegisterListenerRabbitMQ<OffersRegistersSelectReceive, TPaginationRequestStandardModel<RegistersSelectRequestBaseModel>, TPaginationResponseStandardModel<OfferAvailabilityModelDB>>()
            .RegisterListenerRabbitMQ<WarehouseDocumentsSelectReceive, TPaginationRequestStandardModel<WarehouseDocumentsSelectRequestModel>, TPaginationResponseStandardModel<WarehouseDocumentModelDB>>()
            .RegisterListenerRabbitMQ<WarehousesDocumentsReadReceive, int[], TResponseModel<WarehouseDocumentModelDB[]>>()
            .RegisterListenerRabbitMQ<WarehouseDocumentUpdateOrCreateReceive, TAuthRequestStandardModel<WarehouseDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<RowsDeleteFromWarehouseDocumentReceive, TAuthRequestStandardModel<int[]>, TResponseModel<Dictionary<int, DeliveryDocumentMetadataModel>>>()
            .RegisterListenerRabbitMQ<RowForWarehouseDocumentUpdateOrCreateReceive, TAuthRequestStandardModel<RowOfWarehouseDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<StatusOrderChangeByHelpDeskDocumentIdReceive, TAuthRequestStandardModel<StatusChangeRequestModel>, TResponseModel<OrderDocumentModelDB[]>>()
            .RegisterListenerRabbitMQ<PriceRuleDeleteReceive, TAuthRequestStandardModel<PriceRuleDeleteRequestModel>, TResponseModel<PriceRuleForOfferModelDB>>()
            .RegisterListenerRabbitMQ<AttendancesRecordsByIssuesGetReceive, OrdersByIssuesSelectRequestModel, TResponseModel<RecordsAttendanceModelDB[]>>()
            .RegisterListenerRabbitMQ<WorksFindReceive, WorkFindRequestModel, WorksFindResponseModel>()
            .RegisterListenerRabbitMQ<PriceRuleUpdateOrCreateReceive, TAuthRequestStandardModel<PriceRuleForOfferModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<PricesRulesGetForOffersReceive, TAuthRequestStandardModel<int[]>, TResponseModel<List<PriceRuleForOfferModelDB>>>()
            .RegisterListenerRabbitMQ<PaymentDocumentUpdateOrCreateReceive, TAuthRequestStandardModel<PaymentDocumentBaseModel>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<OrderUpdateOrCreateReceive, TAuthRequestStandardModel<OrderDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<OffersReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<OfferModelDB[]>>()
            .RegisterListenerRabbitMQ<FilesForGoodSelectReceive, TPaginationRequestStandardModel<FilesForGoodSelectRequestModel>, TPaginationResponseStandardModel<FileGoodsConfigModelDB>>()
            .RegisterListenerRabbitMQ<FilesForGoodSetReceive, TAuthRequestStandardModel<FilesForGoodSetRequestModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<FileForGoodUpdateReceive, TAuthRequestStandardModel<FileGoodsConfigModelDB>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<MoveFileForGoodsReceive, TAuthRequestStandardModel<MoveMetaObjectModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<NomenclaturesReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<List<NomenclatureModelDB>>>()
            .RegisterListenerRabbitMQ<OfficesOrganizationsReadReceive, int[], TResponseModel<OfficeOrganizationModelDB[]>>()
            .RegisterListenerRabbitMQ<RowsDeleteFromOrderReceive, TAuthRequestStandardModel<int[]>, TResponseModel<RowOrderDocumentRecord[]>>()
            .RegisterListenerRabbitMQ<AttendanceRecordsCreateReceive, TAuthRequestStandardModel<CreateAttendanceRequestModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<RowForOrderUpdateOrCreateReceive, TAuthRequestStandardModel<RowOfOrderDocumentModelDB>, DocumentNewVersionResponseModel>()
            .RegisterListenerRabbitMQ<OrdersReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<OrderDocumentModelDB[]>>()
            .RegisterListenerRabbitMQ<OrganizationOfferContractSetReceive, TAuthRequestStandardModel<OrganizationOfferToggleModel>, ResponseBaseModel>()
            .RegisterListenerRabbitMQ<OrdersSelectReceive, TPaginationRequestStandardModel<TAuthRequestStandardModel<OrdersSelectRequestModel>>, TPaginationResponseStandardModel<OrderDocumentModelDB>>()
            .RegisterListenerRabbitMQ<OfferUpdateOrCreateReceive, TAuthRequestStandardModel<OfferModelDB>, TResponseModel<int>>()
            .RegisterListenerRabbitMQ<OffersSelectReceive, TAuthRequestStandardModel<TPaginationRequestStandardModel<OffersSelectRequestModel>>, TResponseModel<TPaginationResponseStandardModel<OfferModelDB>>>()
            .RegisterListenerRabbitMQ<NomenclaturesSelectReceive, TPaginationRequestStandardModel<NomenclaturesSelectRequestModel>, TPaginationResponseStandardModel<NomenclatureModelDB>>()
            .RegisterListenerRabbitMQ<OrganizationsReadReceive, int[], TResponseModel<OrganizationModelDB[]>>()
            .RegisterListenerRabbitMQ<IncomingMerchantPaymentTBankReceive, IncomingMerchantPaymentTBankNotifyModel, ResponseBaseModel>()
        ;
    }
}