////////////////////////////////////////////////
// © https://github.com/badhitman - @FakeGov 
////////////////////////////////////////////////

using Transmission.Receives.commerce;
using SharedLib;

namespace CommerceService;

/// <summary>
/// MQ listen
/// </summary>
public static class RegisterMqListenerExtension
{
    /// <summary>
    /// RegisterMqListeners
    /// </summary>
    public static IServiceCollection CommerceRegisterMqListeners(this IServiceCollection services)
    {
        return services
            .RegisterMqListener<UpdateWalletTypeReceive, WalletRetailTypeModelDB, ResponseBaseModel>()
            .RegisterMqListener<ToggleWalletTypeDisabledForPaymentTypeReceive, ToggleWalletTypeDisabledForPaymentTypeRequestModel, ResponseBaseModel>()
            .RegisterMqListener<UpdateWalletReceive, WalletRetailModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdateRowOfDeliveryDocumentReceive, RowOfDeliveryRetailDocumentModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdatePaymentDocumentReceive, PaymentRetailDocumentModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdatePaymentOrderLinkDocumentReceive, PaymentOrderRetailLinkModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdateDeliveryStatusDocumentReceive, DeliveryStatusRetailDocumentModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdateDeliveryDocumentReceive, DeliveryDocumentRetailModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdateConversionDocumentReceive, WalletConversionRetailDocumentModelDB, ResponseBaseModel>()
            .RegisterMqListener<DeleteConversionOrderLinkDocumentReceive, DeleteConversionOrderLinkRetailDocumentsRequestModel, ResponseBaseModel>()
            .RegisterMqListener<DeleteToggleConversionReceive, int?, ResponseBaseModel>()
            .RegisterMqListener<UpdateConversionOrderLinkDocumentReceive, ConversionOrderRetailLinkModelDB, ResponseBaseModel>()
            .RegisterMqListener<StatusesOrdersAttendancesChangeByHelpDeskDocumentIdReceive, TAuthRequestStandardModel<StatusChangeRequestModel>, ResponseBaseModel>()
            .RegisterMqListener<SelectWalletsTypesReceive, TPaginationRequestStandardModel<SelectWalletsRetailsTypesRequestModel>, TPaginationResponseStandardModel<WalletRetailTypeViewModel>>()
            .RegisterMqListener<SelectWalletsReceive, TPaginationRequestStandardModel<SelectWalletsRetailsRequestModel>, TPaginationResponseStandardModel<WalletRetailModelDB>>()
            .RegisterMqListener<SelectRowOfDeliveryDocumentsReceive, TPaginationRequestStandardModel<SelectRowsOfDeliveriesRetailDocumentsRequestModel>, TPaginationResponseStandardModel<RowOfDeliveryRetailDocumentModelDB>>()
            .RegisterMqListener<SelectPaymentsDocumentsReceive, TPaginationRequestStandardModel<SelectPaymentsRetailOrdersDocumentsRequestModel>, TPaginationResponseStandardModel<PaymentRetailDocumentModelDB>>()
            .RegisterMqListener<SelectDeliveryStatusesDocumentsReceive, TPaginationRequestStandardModel<SelectDeliveryStatusesRetailDocumentsRequestModel>, TPaginationResponseStandardModel<DeliveryStatusRetailDocumentModelDB>>()
            .RegisterMqListener<SelectDeliveryDocumentsReceive, TPaginationRequestStandardModel<SelectDeliveryDocumentsRetailRequestModel>, TPaginationResponseStandardModel<DeliveryDocumentRetailModelDB>>()
            .RegisterMqListener<SelectConversionsDocumentsReceive, TPaginationRequestStandardModel<SelectWalletsRetailsConversionDocumentsRequestModel>, TPaginationResponseStandardModel<WalletConversionRetailDocumentModelDB>>()
            .RegisterMqListener<SelectConversionsOrdersDocumentsLinksReceive, TPaginationRequestStandardModel<SelectConversionsOrdersLinksRetailDocumentsRequestModel>, TPaginationResponseStandardModel<ConversionOrderRetailLinkModelDB>>()
            .RegisterMqListener<ConversionsOrdersDocumentsLinksReadRetailReceive, int[], TResponseModel<ConversionOrderRetailLinkModelDB[]>>()
            .RegisterMqListener<CreateWalletTypeReceive, WalletRetailTypeModelDB, TResponseModel<int>>()
            .RegisterMqListener<CreateWalletReceive, WalletRetailModelDB, TResponseModel<int>>()
            .RegisterMqListener<CreateRowOfDeliveryDocumentReceive, RowOfDeliveryRetailDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<CreatePaymentDocumentReceive, CreatePaymentRetailDocumentRequestModel, TResponseModel<int>>()
            .RegisterMqListener<FinancialsReportRetailReceive, TPaginationRequestStandardModel<SelectPaymentsRetailReportRequestModel>, TPaginationResponseStandardModel<WalletRetailReportRowModel>>()
            .RegisterMqListener<GetMainReportRetailReceive, MainReportRequestModel, MainReportResponseModel>()
            .RegisterMqListener<AboutPeriodRetailReceive, object, PeriodBaseModel>()
            .RegisterMqListener<OffersOfOrdersReportRetailReceive, TPaginationRequestStandardModel<SelectOffersOfOrdersRetailReportRequestModel>, TPaginationResponseStandardModel<OffersRetailReportRowModel>>()
            .RegisterMqListener<OffersOfDeliveriesReportRetailReceive, TPaginationRequestStandardModel<SelectOffersOfDeliveriesRetailReportRequestModel>, TPaginationResponseStandardModel<OffersRetailReportRowModel>>()
            .RegisterMqListener<DeletePaymentOrderLinkDocumentReceive, DeletePaymentOrderLinkRetailDocumentsRequestModel, ResponseBaseModel>()
            .RegisterMqListener<CreatePaymentOrderLinkDocumentReceive, PaymentOrderRetailLinkModelDB, TResponseModel<int>>()
            .RegisterMqListener<GetPaymentsDocumentsReceive, GetPaymentsRetailOrdersDocumentsRequestModel, TResponseModel<PaymentRetailDocumentModelDB[]>>()
            .RegisterMqListener<CreateDeliveryStatusDocumentReceive, DeliveryStatusRetailDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<CreateDeliveryDocumentReceive, CreateDeliveryDocumentRetailRequestModel, TResponseModel<int>>()
            .RegisterMqListener<GetDeliveriesJournalFileReceive, SelectDeliveryDocumentsRetailRequestModel, FileAttachModel>()
            .RegisterMqListener<DeleteRowOfDeliveryDocumentReceive, int?, ResponseBaseModel>()
            .RegisterMqListener<TotalWeightOrdersLinksDocumentsReceive, TotalWeightDeliveriesOrdersLinksDocumentsRequestModel, TResponseModel<decimal>>()
            .RegisterMqListener<DeleteDeliveryStatusDocumentReceive, int?, ResponseBaseModel>()
            .RegisterMqListener<GetDeliveryDocumentsReceive, GetDeliveryDocumentsRetailRequestModel, TResponseModel<DeliveryDocumentRetailModelDB[]>>()
            .RegisterMqListener<CreateConversionDocumentReceive, CreateWalletConversionRetailDocumentRequestModel, TResponseModel<int>>()
            .RegisterMqListener<GetSumConversionsOrdersAmountsReceive, GetSumConversionsOrdersAmountsRequestModel, TResponseModel<decimal>>()
            .RegisterMqListener<CreateConversionOrderLinkDocumentReceive, ConversionOrderRetailLinkModelDB, TResponseModel<int>>()
            .RegisterMqListener<GetConversionsDocumentsReceive, ReadWalletsRetailsConversionDocumentsRequestModel, TResponseModel<WalletConversionRetailDocumentModelDB[]>>()
            .RegisterMqListener<WalletsTypesGetReceive, int[], TResponseModel<WalletRetailTypeViewModel[]>>()
            .RegisterMqListener<SelectRetailDocumentsReceive, TPaginationRequestStandardModel<SelectRetailDocumentsRequestModel>, TPaginationResponseStandardModel<DocumentRetailModelDB>>()
            .RegisterMqListener<SelectPaymentsOrdersDocumentsLinksReceive, TPaginationRequestStandardModel<SelectPaymentsOrdersLinksRetailDocumentsRequestModel>, TPaginationResponseStandardModel<PaymentOrderRetailLinkModelDB>>()
            .RegisterMqListener<PaymentsOrdersDocumentsLinksGetReceive, int[], TResponseModel<PaymentOrderRetailLinkModelDB[]>>()
            .RegisterMqListener<SelectOrderDocumentStatusesReceive, TPaginationRequestStandardModel<SelectOrderStatusesRetailDocumentsRequestModel>, TPaginationResponseStandardModel<OrderStatusRetailDocumentModelDB>>()
            .RegisterMqListener<CreateRetailDocumentReceive, CreateDocumentRetailRequestModel, TResponseModel<int>>()
            .RegisterMqListener<CreateDeliveryOrderLinkDocumentReceive, RetailOrderDeliveryLinkModelDB, TResponseModel<int>>()
            .RegisterMqListener<CreateOrderStatusDocumentReceive, OrderStatusRetailDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<DeleteDeliveryOrderLinkDocumentReceive, DeleteDeliveryOrderLinkRetailDocumentsRequestModel, ResponseBaseModel>()
            .RegisterMqListener<DeleteRowRetailDocumentReceive, DeleteRowRetailDocumentRequestModel, TResponseModel<Guid?>>()
            .RegisterMqListener<DeleteOrderStatusDocumentReceive, int?, ResponseBaseModel>()
            .RegisterMqListener<UpdateDeliveryOrderLinkDocumentReceive, RetailOrderDeliveryLinkModelDB, ResponseBaseModel>()
            .RegisterMqListener<SelectDeliveriesOrdersLinksDocumentsReceive, TPaginationRequestStandardModel<SelectDeliveriesOrdersLinksRetailDocumentsRequestModel>, TPaginationResponseStandardModel<RetailOrderDeliveryLinkModelDB>>()
            .RegisterMqListener<DeliveriesOrdersLinksDocumentsReadReceive, int[], TResponseModel<RetailOrderDeliveryLinkModelDB[]>>()
            .RegisterMqListener<UpdateRetailDocumentReceive, DocumentRetailModelDB, ResponseBaseModel>()
            .RegisterMqListener<UpdateOrderStatusDocumentReceive, OrderStatusRetailDocumentModelDB, ResponseBaseModel>()
            .RegisterMqListener<RetailDocumentsGetReceive, RetailDocumentsGetRequestModel, TResponseModel<DocumentRetailModelDB[]>>()
            .RegisterMqListener<CreateRowRetailDocumentReceive, RowOfRetailOrderDocumentModelDB, TResponseModel<KeyValuePair<int, Guid>?>>()
            .RegisterMqListener<SelectRowsRetailDocumentsReceive, TPaginationRequestStandardModel<SelectRowsRetailDocumentsRequestModel>, TPaginationResponseStandardModel<RowOfRetailOrderDocumentModelDB>>()
            .RegisterMqListener<UpdateRowRetailDocumentReceive, RowOfRetailOrderDocumentModelDB, TResponseModel<Guid?>>()
            .RegisterMqListener<OrganizationSetLegalReceive, OrganizationLegalModel, TResponseModel<bool>>()
            .RegisterMqListener<OrganizationUpdateReceive, TAuthRequestStandardModel<OrganizationModelDB>, TResponseModel<int>>()
            .RegisterMqListener<OrganizationsSelectReceive, TPaginationRequestAuthModel<OrganizationsSelectRequestModel>, TPaginationResponseStandardModel<OrganizationModelDB>>()
            .RegisterMqListener<OfficeOrganizationUpdateOrCreateReceive, AddressOrganizationBaseModel, TResponseModel<int>>()
            .RegisterMqListener<OfficeOrganizationDeleteReceive, int, ResponseBaseModel>()
            .RegisterMqListener<RecordsAttendancesSelectReceive, TPaginationRequestAuthModel<RecordsAttendancesRequestModel>, TPaginationResponseStandardModel<RecordsAttendanceModelDB>>()
            .RegisterMqListener<NomenclatureUpdateOrCreateReceive, NomenclatureModelDB, TResponseModel<int>>()
            .RegisterMqListener<OrdersByIssuesGetReceive, OrdersByIssuesSelectRequestModel, TResponseModel<OrderDocumentModelDB[]>>()
            .RegisterMqListener<UploadOffersReceive, List<NomenclatureScopeModel>, ResponseBaseModel>()
            .RegisterMqListener<AttendanceRecordsDeleteReceive, TAuthRequestStandardModel<int[]>, TResponseModel<RecordsAttendanceModelDB[]>>()
            .RegisterMqListener<UserOrganizationUpdateReceive, TAuthRequestStandardModel<UserOrganizationModelDB>, TResponseModel<int>>()
            .RegisterMqListener<UsersOrganizationsReadReceive, int[], TResponseModel<UserOrganizationModelDB[]>>()
            .RegisterMqListener<UsersOrganizationsSelectReceive, TPaginationRequestAuthModel<UsersOrganizationsStatusesRequestModel>, TResponseModel<TPaginationResponseStandardModel<UserOrganizationModelDB>>>()
            .RegisterMqListener<BankDetailsForOrganizationDeleteReceive, TAuthRequestStandardModel<int>, TResponseModel<BankDetailsModelDB>>()
            .RegisterMqListener<BankDetailsUpdateOrCreateReceive, TAuthRequestStandardModel<BankDetailsModelDB>, TResponseModel<int>>()
            .RegisterMqListener<WeeklyScheduleCreateOrUpdateReceive, WeeklyScheduleModelDB, TResponseModel<int>>()
            .RegisterMqListener<WeeklySchedulesSelectReceive, TPaginationRequestStandardModel<WorkSchedulesSelectRequestModel>, TPaginationResponseStandardModel<WeeklyScheduleModelDB>>()
            .RegisterMqListener<WeeklySchedulesReadReceive, int[], List<WeeklyScheduleModelDB>>()
            .RegisterMqListener<CalendarScheduleUpdateOrCreateReceive, TAuthRequestStandardModel<CalendarScheduleModelDB>, TResponseModel<int>>()
            .RegisterMqListener<CalendarsSchedulesSelectReceive, TAuthRequestStandardModel<TPaginationRequestStandardModel<WorkScheduleCalendarsSelectRequestModel>>, TResponseModel<TPaginationResponseStandardModel<CalendarScheduleModelDB>>>()
            .RegisterMqListener<CalendarsSchedulesReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<List<CalendarScheduleModelDB>>>()
            .RegisterMqListener<PriceFullFileGetExcelReceive, object, FileAttachModel>()
            .RegisterMqListener<PriceFullFileGetJsonReceive, object, FileAttachModel>()
            .RegisterMqListener<OrderReportGetReceive, TAuthRequestStandardModel<int>, TResponseModel<FileAttachModel>>()
            .RegisterMqListener<OffersRegistersSelectReceive, TPaginationRequestStandardModel<RegistersSelectRequestBaseModel>, TPaginationResponseStandardModel<OfferAvailabilityModelDB>>()
            .RegisterMqListener<WarehousesSelectReceive, TPaginationRequestStandardModel<WarehouseDocumentsSelectRequestModel>, TPaginationResponseStandardModel<WarehouseDocumentModelDB>>()
            .RegisterMqListener<WarehousesDocumentsReadReceive, int[], TResponseModel<WarehouseDocumentModelDB[]>>()
            .RegisterMqListener<WarehouseDocumentUpdateReceive, WarehouseDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<RowsForWarehouseDocumentDeleteReceive, int[], RowsForWarehouseDocumentDeleteResponseModel>()
            .RegisterMqListener<RowForWarehouseDocumentUpdateReceive, RowOfWarehouseDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<StatusOrderChangeByHelpDeskDocumentIdReceive, TAuthRequestStandardModel<StatusChangeRequestModel>, ResponseBaseModel>()
            .RegisterMqListener<PriceRuleDeleteReceive, TAuthRequestStandardModel<int>, TResponseModel<List<PriceRuleForOfferModelDB>>>()
            .RegisterMqListener<AttendancesRecordsByIssuesGetReceive, OrdersByIssuesSelectRequestModel, TResponseModel<RecordsAttendanceModelDB[]>>()
            .RegisterMqListener<WorksFindReceive, WorkFindRequestModel, WorksFindResponseModel>()
            .RegisterMqListener<PriceRuleUpdateReceive, TAuthRequestStandardModel<PriceRuleForOfferModelDB>, TResponseModel<int>>()
            .RegisterMqListener<PricesRulesGetForOffersReceive, TAuthRequestStandardModel<int[]>, TResponseModel<List<PriceRuleForOfferModelDB>>>()
            .RegisterMqListener<PaymentDocumentUpdateReceive, TAuthRequestStandardModel<PaymentDocumentBaseModel>, TResponseModel<int>>()
            .RegisterMqListener<OrderUpdateOrCreateReceive, OrderDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<OffersReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<OfferModelDB[]>>()
            .RegisterMqListener<NomenclaturesReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<List<NomenclatureModelDB>>>()
            .RegisterMqListener<OfficesOrganizationsReadReceive, int[], TResponseModel<OfficeOrganizationModelDB[]>>()
            .RegisterMqListener<PaymentDocumentDeleteReceive, TAuthRequestStandardModel<int>, ResponseBaseModel>()
            .RegisterMqListener<RowsDeleteFromOrderReceive, int[], TResponseModel<RowOrderDocumentRecord[]>>()
            .RegisterMqListener<AttendanceRecordsCreateReceive, TAuthRequestStandardModel<CreateAttendanceRequestModel>, ResponseBaseModel>()
            .RegisterMqListener<RowForOrderUpdateOrCreateReceive, RowOfOrderDocumentModelDB, TResponseModel<int>>()
            .RegisterMqListener<OrdersReadReceive, TAuthRequestStandardModel<int[]>, TResponseModel<OrderDocumentModelDB[]>>()
            .RegisterMqListener<OrganizationOfferContractUpdateReceive, TAuthRequestStandardModel<OrganizationOfferToggleModel>, TResponseModel<bool>>()
            .RegisterMqListener<OrdersSelectReceive, TPaginationRequestStandardModel<TAuthRequestStandardModel<OrdersSelectRequestModel>>, TPaginationResponseStandardModel<OrderDocumentModelDB>>()
            .RegisterMqListener<OfferUpdateOrCreateReceive, TAuthRequestStandardModel<OfferModelDB>, TResponseModel<int>>()
            .RegisterMqListener<OffersSelectReceive, TAuthRequestStandardModel<TPaginationRequestStandardModel<OffersSelectRequestModel>>, TResponseModel<TPaginationResponseStandardModel<OfferModelDB>>>()
            .RegisterMqListener<NomenclaturesSelectReceive, TPaginationRequestStandardModel<NomenclaturesSelectRequestModel>, TPaginationResponseStandardModel<NomenclatureModelDB>>()
            .RegisterMqListener<OrganizationsReadReceive, int[], TResponseModel<OrganizationModelDB[]>>()
            .RegisterMqListener<IncomingMerchantPaymentTBankReceive, IncomingMerchantPaymentTBankNotifyModel, ResponseBaseModel>()
        ;
    }
}