////////////////////////////////////////////////
// © https://github.com/badhitman - @FakeGov 
////////////////////////////////////////////////

using System.Collections.Generic;

namespace SharedLib;

/// <inheritdoc/>
public static class Extensions
{
    /// <inheritdoc/>
    public static readonly Dictionary<int, CurrencyItem> CurrenciesCodes = new()
    {
        {784, new("AED","United Arab Emirates dirham")},{971, new("AFN","Afghan afghani")},
        {8, new("ALL","Albanian lek")},{51, new("AMD","Armenian dram")},
        {973, new("AOA","Angolan kwanza")},{32, new("ARS","Argentine peso")},
        {36, new("AUD","Australian dollar")},{533, new("AWG","Aruban florin")},
        {944, new("AZN","Azerbaijani manat")},{977, new("BAM","Bosnia and Herzegovina convertible mark")},
        {52, new("BBD","Barbados dollar")},{50, new("BDT","Bangladeshi taka")},
        {975, new("BGN","Bulgarian lev")},{48, new("BHD","Bahraini dinar")},
        {108, new("BIF","Burundian franc")},{60, new("BMD","Bermudian dollar")},
        {96, new("BND","Brunei dollar")},{68, new("BOB","Boliviano")},
        {984, new("BOV","Bolivian Mvdol (funds code)")},{986, new("BRL","Brazilian real")},
        {44, new("BSD","Bahamian dollar")},{64, new("BTN","Bhutanese ngultrum")},
        {72, new("BWP","Botswana pula")},{933, new("BYN","Belarusian ruble")},
        {84, new("BZD","Belize dollar")},{124, new("CAD","Canadian dollar")},
        {976, new("CDF","Congolese franc")},{947, new("CHE","WIR euro (complementary currency)")},
        {756, new("CHF","Swiss franc")},{948, new("CHW","WIR franc (complementary currency)")},
        {990, new("CLF","Unidad de Fomento (funds code)")},{152, new("CLP","Chilean peso")},
        {156, new("CNY","Renminbi[6]")},{170, new("COP","Colombian peso")},
        {970, new("COU","Unidad de Valor Real (UVR) (funds code)[7]")},{188, new("CRC","Costa Rican colon")},
        {192, new("CUP","Cuban peso")},{132, new("CVE","Cape Verdean escudo")},
        {203, new("CZK","Czech koruna")},{262, new("DJF","Djiboutian franc")},
        {208, new("DKK","Danish krone")},{214, new("DOP","Dominican peso")},
        {12, new("DZD","Algerian dinar")},{818, new("EGP","Egyptian pound")},
        {232, new("ERN","Eritrean nakfa")},{230, new("ETB","Ethiopian birr")},
        {978, new("EUR","Euro")},{242, new("FJD","Fiji dollar")},
        {238, new("FKP","Falkland Islands pound")},{826, new("GBP","Pound sterling")},
        {981, new("GEL","Georgian lari")},{936, new("GHS","Ghanaian cedi")},
        {292, new("GIP","Gibraltar pound")},{270, new("GMD","Gambian dalasi")},
        {324, new("GNF","Guinean franc")},{320, new("GTQ","Guatemalan quetzal")},
        {328, new("GYD","Guyanese dollar")},{344, new("HKD","Hong Kong dollar")},
        {340, new("HNL","Honduran lempira")},{332, new("HTG","Haitian gourde")},
        {348, new("HUF","Hungarian forint")},{360, new("IDR","Indonesian rupiah")},
        {376, new("ILS","Israeli new shekel")},{356, new("INR","Indian rupee")},
        {368, new("IQD","Iraqi dinar")},{364, new("IRR","Iranian rial")},
        {352, new("ISK","Icelandic króna (plural: krónur)")},{388, new("JMD","Jamaican dollar")},
        {400, new("JOD","Jordanian dinar")},{392, new("JPY","Japanese yen")},
        {404, new("KES","Kenyan shilling")},{417, new("KGS","Kyrgyzstani som")},
        {116, new("KHR","Cambodian riel")},{174, new("KMF","Comoro franc")},
        {408, new("KPW","North Korean won")},{410, new("KRW","South Korean won")},
        {414, new("KWD","Kuwaiti dinar")},{136, new("KYD","Cayman Islands dollar")},
        {398, new("KZT","Kazakhstani tenge")},{418, new("LAK","Lao kip")},
        {422, new("LBP","Lebanese pound")},{144, new("LKR","Sri Lankan rupee")},
        {430, new("LRD","Liberian dollar")},{426, new("LSL","Lesotho loti")},
        {434, new("LYD","Libyan dinar")},{504, new("MAD","Moroccan dirham")},
        {498, new("MDL","Moldovan leu")},{969, new("MGA","Malagasy ariary")},
        {807, new("MKD","Macedonian denar")},{104, new("MMK","Myanmar kyat")},
        {496, new("MNT","Mongolian tögrög")},{446, new("MOP","Macanese pataca")},
        {929, new("MRU","Mauritanian ouguiya")},{480, new("MUR","Mauritian rupee")},
        {462, new("MVR","Maldivian rufiyaa")},{454, new("MWK","Malawian kwacha")},
        {484, new("MXN","Mexican peso")},{979, new("MXV","Mexican Unidad de Inversion (UDI) (funds code)")},
        {458, new("MYR","Malaysian ringgit")},{943, new("MZN","Mozambican metical")},
        {516, new("NAD","Namibian dollar")},{566, new("NGN","Nigerian naira")},
        {558, new("NIO","Nicaraguan córdoba")},{578, new("NOK","Norwegian krone")},
        {524, new("NPR","Nepalese rupee")},{554, new("NZD","New Zealand dollar")},
        {512, new("OMR","Omani rial")},{590, new("PAB","Panamanian balboa")},
        {604, new("PEN","Peruvian sol")},{598, new("PGK","Papua New Guinean kina")},
        {608, new("PHP","Philippine peso[11]")},{586, new("PKR","Pakistani rupee")},
        {985, new("PLN","Polish złoty")},{600, new("PYG","Paraguayan guaraní")},
        {634, new("QAR","Qatari riyal")},{946, new("RON","Romanian leu")},
        {941, new("RSD","Serbian dinar")},{643, new("RUB","Russian ruble")},
        {646, new("RWF","Rwandan franc")},{682, new("SAR","Saudi riyal")},
        {90, new("SBD","Solomon Islands dollar")},{690, new("SCR","Seychelles rupee")},
        {938, new("SDG","Sudanese pound")},{752, new("SEK","Swedish krona (plural: kronor)")},
        {702, new("SGD","Singapore dollar")},{654, new("SHP","Saint Helena pound")},
        {925, new("SLE","Sierra Leonean leone (new leone)[12][13][14]")},{706, new("SOS","Somalian shilling")},
        {968, new("SRD","Surinamese dollar")},{728, new("SSP","South Sudanese pound")},
        {930, new("STN","São Tomé and Príncipe dobra")},{222, new("SVC","Salvadoran colón")},
        {760, new("SYP","Syrian pound")},{748, new("SZL","Swazi lilangeni")},
        {764, new("THB","Thai baht")},{972, new("TJS","Tajikistani somoni")},
        {934, new("TMT","Turkmenistan manat")},{788, new("TND","Tunisian dinar")},
        {776, new("TOP","Tongan paʻanga")},{949, new("TRY","Turkish lira")},
        {780, new("TTD","Trinidad and Tobago dollar")},{901, new("TWD","New Taiwan dollar")},
        {834, new("TZS","Tanzanian shilling")},{980, new("UAH","Ukrainian hryvnia")},
        {800, new("UGX","Ugandan shilling")},{840, new("USD","United States dollar")},
        {997, new("USN","United States dollar (next day) (funds code)")},{940, new("UYI","Uruguay Peso en Unidades Indexadas (URUIURUI) (funds code)")},
        {858, new("UYU","Uruguayan peso")},{927, new("UYW","Unidad previsional[16]")},
        {860, new("UZS","Uzbekistani sum")},{926, new("VED","Venezuelan digital bolívar[17]")},
        {928, new("VES","Venezuelan sovereign bolívar[11]")},{704, new("VND","Vietnamese đồng")},
        {548, new("VUV","Vanuatu vatu")},{882, new("WST","Samoan tala")},
        {396, new("XAD","Arab Accounting Dinar[18]")},{950, new("XAF","CFA franc BEAC")},
        {961, new("XAG","Silver (one troy ounce)")},{959, new("XAU","Gold (one troy ounce)")},
        {955, new("XBA","European Composite Unit (EURCO) (bond market unit)")},{956, new("XBB","European Monetary Unit (E.M.U.-6) (bond market unit)")},
        {957, new("XBC","European Unit of Account 9 (E.U.A.-9) (bond market unit)")},{958, new("XBD","European Unit of Account 17 (E.U.A.-17) (bond market unit)")},
        {951, new("XCD","East Caribbean dollar")},{532, new("XCG","Caribbean guilder")},
        {960, new("XDR","Special drawing rights")},{952, new("XOF","CFA franc BCEAO")},
        {964, new("XPD","Palladium (one troy ounce)")},{953, new("XPF","CFP franc (franc Pacifique)")},
        {962, new("XPT","Platinum (one troy ounce)")},{994, new("XSU","SUCRE")},
        {963, new("XTS","Code reserved for testing")},{965, new("XUA","ADB Unit of Account")},
        {999, new("XXX","No currency")},{886, new("YER","Yemeni rial")},
        {710, new("ZAR","South African rand")},{967, new("ZMW","Zambian kwacha")},{924, new("ZWG","Zimbabwe Gold")}
    };
    /// <inheritdoc/>
    public record struct CurrencyItem(string SymbolCode, string Name);
}