// <auto-generated />
using System;
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbPostgreLib.Migrations
{
    [DbContext(typeof(MainAppContext))]
    [Migration("20260204161433_MainAppContext001")]
    partial class MainAppContext001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLib.AttachesMessageWebChatModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FileAttachId")
                        .HasColumnType("integer");

                    b.Property<string>("FileAttachName")
                        .HasColumnType("text");

                    b.Property<long>("FileLength")
                        .HasColumnType("bigint");

                    b.Property<string>("FileTokenAccess")
                        .HasColumnType("text");

                    b.Property<int>("MessageOwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageOwnerId");

                    b.ToTable("AttachesFilesOfMessages");
                });

            modelBuilder.Entity("SharedLib.DialogWebChatModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeadlineUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorContacts")
                        .HasColumnType("text");

                    b.Property<string>("InitiatorContactsNormalized")
                        .HasColumnType("text");

                    b.Property<string>("InitiatorHumanName")
                        .HasColumnType("text");

                    b.Property<string>("InitiatorIdentityId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastMessageAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastOnlineAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SessionTicketId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DeadlineUTC");

                    b.HasIndex("InitiatorContacts");

                    b.HasIndex("InitiatorContactsNormalized");

                    b.HasIndex("InitiatorIdentityId");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("LastMessageAtUTC");

                    b.HasIndex("LastOnlineAtUTC");

                    b.HasIndex("SessionTicketId")
                        .IsUnique();

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("SharedLib.MessageWebChatModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DialogOwnerId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsInsideMessage")
                        .HasColumnType("boolean");

                    b.Property<string>("SenderUserIdentityId")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("DialogOwnerId");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("SenderUserIdentityId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SharedLib.UserJoinDialogWebChatModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DialogJoinId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OutDateUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserIdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DialogJoinId");

                    b.HasIndex("JoinedDateUTC");

                    b.HasIndex("OutDateUTC");

                    b.HasIndex("UserIdentityId");

                    b.ToTable("UsersDialogsJoins");
                });

            modelBuilder.Entity("SharedLib.AttachesMessageWebChatModelDB", b =>
                {
                    b.HasOne("SharedLib.MessageWebChatModelDB", "MessageOwner")
                        .WithMany("AttachesFiles")
                        .HasForeignKey("MessageOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MessageOwner");
                });

            modelBuilder.Entity("SharedLib.MessageWebChatModelDB", b =>
                {
                    b.HasOne("SharedLib.DialogWebChatModelDB", "DialogOwner")
                        .WithMany()
                        .HasForeignKey("DialogOwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DialogOwner");
                });

            modelBuilder.Entity("SharedLib.UserJoinDialogWebChatModelDB", b =>
                {
                    b.HasOne("SharedLib.DialogWebChatModelDB", "DialogJoin")
                        .WithMany("UsersJoins")
                        .HasForeignKey("DialogJoinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DialogJoin");
                });

            modelBuilder.Entity("SharedLib.DialogWebChatModelDB", b =>
                {
                    b.Navigation("UsersJoins");
                });

            modelBuilder.Entity("SharedLib.MessageWebChatModelDB", b =>
                {
                    b.Navigation("AttachesFiles");
                });
#pragma warning restore 612, 618
        }
    }
}
