// <auto-generated />
using System;
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbPostgreLib.Migrations
{
    [DbContext(typeof(MainAppContext))]
    [Migration("20260201194208_MainAppContext001")]
    partial class MainAppContext001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLib.DialogWebChatModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeadlineUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InitiatorContacts")
                        .HasColumnType("text");

                    b.Property<string>("InitiatorHumanName")
                        .HasColumnType("text");

                    b.Property<string>("InitiatorIdentityId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastMessageAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastReadAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeadlineUTC");

                    b.HasIndex("InitiatorContacts");

                    b.HasIndex("InitiatorIdentityId");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("LastMessageAtUTC");

                    b.HasIndex("LastReadAtUTC");

                    b.ToTable("Dialogs");
                });
#pragma warning restore 612, 618
        }
    }
}
