// <auto-generated />
using System;
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StockSharpDriver.Migrations
{
    [DbContext(typeof(StockSharpAppContext))]
    [Migration("20250426134223_StockSharpAppContext001")]
    partial class StockSharpAppContext001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("SharedLib.BoardStockSharpModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExchangeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAtUpdatedUTC")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("ExchangeId");

                    b.HasIndex("LastAtUpdatedUTC");

                    b.ToTable("Boards");
                });

            modelBuilder.Entity("SharedLib.ExchangeStockSharpModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Exchanges");
                });

            modelBuilder.Entity("SharedLib.InstrumentExternalIdModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bloomberg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cusip")
                        .HasColumnType("TEXT");

                    b.Property<string>("IQFeed")
                        .HasColumnType("TEXT");

                    b.Property<int?>("InteractiveBrokers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Isin")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastAtUpdatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<int>("ParentInstrumentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Plaza")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ric")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sedol")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Bloomberg");

                    b.HasIndex("Cusip");

                    b.HasIndex("IQFeed");

                    b.HasIndex("InteractiveBrokers");

                    b.HasIndex("Isin");

                    b.HasIndex("LastAtUpdatedUTC");

                    b.HasIndex("ParentInstrumentId")
                        .IsUnique();

                    b.HasIndex("Plaza");

                    b.HasIndex("Ric");

                    b.HasIndex("Sedol");

                    b.ToTable("ExternalsIdsInstruments");
                });

            modelBuilder.Entity("SharedLib.InstrumentTradeModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CfiCode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Class")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Decimals")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("ExpiryDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FaceValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdRemote")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAtUpdatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Multiplier")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("OptionStyle")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OptionType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrimaryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SettlementDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SettlementType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ShortName")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Shortable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TypeInstrument")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UnderlyingSecurityId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("UnderlyingSecurityType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("CfiCode");

                    b.HasIndex("Class");

                    b.HasIndex("Code");

                    b.HasIndex("IdRemote");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("LastAtUpdatedUTC");

                    b.HasIndex("PrimaryId");

                    b.HasIndex("UnderlyingSecurityId");

                    b.ToTable("Instruments");
                });

            modelBuilder.Entity("SharedLib.PortfolioTradeModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BoardId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientCode")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Currency")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepoName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastAtUpdatedUTC")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BoardId");

                    b.HasIndex("IsFavorite");

                    b.HasIndex("LastAtUpdatedUTC");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("SharedLib.BoardStockSharpModelDB", b =>
                {
                    b.HasOne("SharedLib.ExchangeStockSharpModelDB", "Exchange")
                        .WithMany("Boards")
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exchange");
                });

            modelBuilder.Entity("SharedLib.InstrumentExternalIdModelDB", b =>
                {
                    b.HasOne("SharedLib.InstrumentTradeModelDB", "ParentInstrument")
                        .WithOne("ExternalId")
                        .HasForeignKey("SharedLib.InstrumentExternalIdModelDB", "ParentInstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParentInstrument");
                });

            modelBuilder.Entity("SharedLib.InstrumentTradeModelDB", b =>
                {
                    b.HasOne("SharedLib.BoardStockSharpModelDB", "Board")
                        .WithMany("Instruments")
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("SharedLib.PortfolioTradeModelDB", b =>
                {
                    b.HasOne("SharedLib.BoardStockSharpModelDB", "Board")
                        .WithMany()
                        .HasForeignKey("BoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Board");
                });

            modelBuilder.Entity("SharedLib.BoardStockSharpModelDB", b =>
                {
                    b.Navigation("Instruments");
                });

            modelBuilder.Entity("SharedLib.ExchangeStockSharpModelDB", b =>
                {
                    b.Navigation("Boards");
                });

            modelBuilder.Entity("SharedLib.InstrumentTradeModelDB", b =>
                {
                    b.Navigation("ExternalId");
                });
#pragma warning restore 612, 618
        }
    }
}
