// <auto-generated />
using System;
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbPostgreLib.Migrations.Commerce
{
    [DbContext(typeof(CommerceContext))]
    partial class CommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLib.BankDetailsModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BankAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BankBIC")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrespondentAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentAccount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("BankBIC", "CorrespondentAccount", "CurrentAccount")
                        .IsUnique();

                    b.ToTable("BanksDetails");
                });

            modelBuilder.Entity("SharedLib.CalendarScheduleModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DateScheduleCalendar")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("EndPart")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedNameUpper")
                        .HasColumnType("text");

                    b.Property<int?>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<long>("QueueCapacity")
                        .HasColumnType("bigint");

                    b.Property<long>("SortIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("StartPart")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContextName");

                    b.HasIndex("DateScheduleCalendar");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("NormalizedNameUpper");

                    b.HasIndex("OfferId");

                    b.HasIndex("StartPart", "EndPart");

                    b.HasIndex("SortIndex", "ParentId", "ContextName")
                        .IsUnique();

                    b.ToTable("CalendarsSchedules");
                });

            modelBuilder.Entity("SharedLib.DeliveryDocumentRetailModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressUserComment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeliveryCode")
                        .HasColumnType("text");

                    b.Property<bool>("DeliveryPaymentUponReceipt")
                        .HasColumnType("boolean");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("KladrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KladrTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<string>("RecipientIdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ShippingCost")
                        .HasColumnType("numeric");

                    b.Property<decimal>("WeightShipping")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("AddressUserComment");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("DeliveryCode");

                    b.HasIndex("DeliveryPaymentUponReceipt");

                    b.HasIndex("DeliveryType");

                    b.HasIndex("KladrCode");

                    b.HasIndex("KladrTitle");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("OrderId");

                    b.HasIndex("RecipientIdentityUserId");

                    b.ToTable("DeliveryRetailDocuments");
                });

            modelBuilder.Entity("SharedLib.DeliveryServiceRetailModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.ToTable("DeliveryRetailServices");
                });

            modelBuilder.Entity("SharedLib.DeliveryStatusRetailDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryDocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("DeliveryDocumentId");

                    b.HasIndex("DeliveryStatus");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.ToTable("DeliveryStatusesRetailDocuments");
                });

            modelBuilder.Entity("SharedLib.LockTransactionModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LockerAreaId")
                        .HasColumnType("integer");

                    b.Property<int>("LockerId")
                        .HasColumnType("integer");

                    b.Property<string>("LockerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LockerId", "LockerName", "LockerAreaId")
                        .IsUnique();

                    b.ToTable("LockTransactions");
                });

            modelBuilder.Entity("SharedLib.NomenclatureModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BaseUnit")
                        .HasColumnType("integer");

                    b.Property<string>("ContextName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedNameUpper")
                        .HasColumnType("text");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<long>("SortIndex")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ContextName");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedNameUpper");

                    b.HasIndex("SortIndex", "ParentId", "ContextName")
                        .IsUnique();

                    b.ToTable("Nomenclatures");
                });

            modelBuilder.Entity("SharedLib.OfferAvailabilityModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OfferId");

                    b.HasIndex("Quantity");

                    b.HasIndex("WarehouseId", "OfferId")
                        .IsUnique();

                    b.ToTable("OffersAvailability");
                });

            modelBuilder.Entity("SharedLib.OfferModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Multiplicity")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferUnit")
                        .HasColumnType("integer");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("QuantitiesTemplate")
                        .HasColumnType("text");

                    b.Property<string>("ShortName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("NomenclatureId");

                    b.ToTable("Offers");
                });

            modelBuilder.Entity("SharedLib.OfficeOrganizationModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressUserComment")
                        .HasColumnType("text");

                    b.Property<string>("Contacts")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KladrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KladrTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Offices");
                });

            modelBuilder.Entity("SharedLib.OrderDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorIdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalDocumentId")
                        .HasColumnType("text");

                    b.Property<int?>("HelpDeskId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<int>("StatusDocument")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ExternalDocumentId", "HelpDeskId", "AuthorIdentityUserId", "StatusDocument");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SharedLib.OrganizationContractorModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OfferId");

                    b.HasIndex("OrganizationId", "OfferId")
                        .IsUnique();

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("SharedLib.OrganizationModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BankMainAccount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("INN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("KPP")
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LegalAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NewINN")
                        .HasColumnType("text");

                    b.Property<string>("NewKPP")
                        .HasColumnType("text");

                    b.Property<string>("NewLegalAddress")
                        .HasColumnType("text");

                    b.Property<string>("NewName")
                        .HasColumnType("text");

                    b.Property<string>("NewOGRN")
                        .HasColumnType("text");

                    b.Property<string>("OGRN")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("INN")
                        .IsUnique();

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("OGRN")
                        .IsUnique();

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("SharedLib.PaymentDocumentModelDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("ExternalDocumentId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailDeliveryLinkModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("DeliveryDocumentId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDocumentId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentsDeliveriesDocumentsRetailLinks");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayerIdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaymentSource")
                        .HasColumnType("text");

                    b.Property<int>("StatusPayment")
                        .HasColumnType("integer");

                    b.Property<int>("TypePayment")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("WalletId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("PayerIdentityUserId");

                    b.HasIndex("PaymentSource");

                    b.HasIndex("StatusPayment");

                    b.HasIndex("TypePayment");

                    b.HasIndex("WalletId");

                    b.ToTable("PaymentsRetailDocuments");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailOrderLinkModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("PaymentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("PaymentId");

                    b.ToTable("PaymentsOrdersRetailLinks");
                });

            modelBuilder.Entity("SharedLib.PriceRuleForOfferModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PriceRule")
                        .HasColumnType("numeric");

                    b.Property<decimal>("QuantityRule")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("OfferId", "QuantityRule")
                        .IsUnique();

                    b.ToTable("PricesRules");
                });

            modelBuilder.Entity("SharedLib.RecordsAttendanceModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorIdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("DateExecute")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<TimeOnly>("EndPart")
                        .HasColumnType("time without time zone");

                    b.Property<string>("ExternalDocumentId")
                        .HasColumnType("text");

                    b.Property<int?>("HelpDeskId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<TimeOnly>("StartPart")
                        .HasColumnType("time without time zone");

                    b.Property<int>("StatusDocument")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OfferId");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("ExternalDocumentId", "HelpDeskId", "AuthorIdentityUserId", "StatusDocument");

                    b.ToTable("AttendancesReg");
                });

            modelBuilder.Entity("SharedLib.RetailDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorIdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuyerIdentityUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalDocumentId")
                        .HasColumnType("text");

                    b.Property<int?>("HelpDeskId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StatusDocument")
                        .HasColumnType("integer");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuyerIdentityUserId");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ExternalDocumentId", "HelpDeskId", "AuthorIdentityUserId", "StatusDocument");

                    b.ToTable("RetailOrders");
                });

            modelBuilder.Entity("SharedLib.RowOfDeliveryRetailDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("DocumentId")
                        .HasColumnType("integer");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DocumentId");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OfferId");

                    b.HasIndex("Quantity");

                    b.ToTable("RowsDeliveryRetailDocuments");
                });

            modelBuilder.Entity("SharedLib.RowOfOrderDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficeOrderTabId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OfferId");

                    b.HasIndex("OfficeOrderTabId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Quantity");

                    b.HasIndex("OfficeOrderTabId", "OfferId")
                        .IsUnique();

                    b.ToTable("RowsOrders");
                });

            modelBuilder.Entity("SharedLib.RowOfRetailOrderDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OfferId");

                    b.HasIndex("OrderId");

                    b.HasIndex("Quantity");

                    b.ToTable("RowsRetailsOrders");
                });

            modelBuilder.Entity("SharedLib.RowOfWarehouseDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<int>("OfferId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("WarehouseDocumentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("OfferId");

                    b.HasIndex("Quantity");

                    b.HasIndex("WarehouseDocumentId");

                    b.HasIndex("WarehouseDocumentId", "OfferId")
                        .IsUnique();

                    b.ToTable("RowsWarehouses");
                });

            modelBuilder.Entity("SharedLib.TabOfficeForOrderModelDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OfficeId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OfficeId");

                    b.HasIndex("OrderId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("OfficesOrders");
                });

            modelBuilder.Entity("SharedLib.UserOrganizationModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("UserPersonIdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserStatus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserPersonIdentityId");

                    b.HasIndex("UserStatus");

                    b.HasIndex("OrganizationId", "UserPersonIdentityId")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("SharedLib.WalletConversionRetailDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("FromWalletId")
                        .HasColumnType("integer");

                    b.Property<decimal>("FromWalletSum")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ToWalletId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ToWalletSum")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("FromWalletId");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("ToWalletId");

                    b.ToTable("ConversionsDocumentsWalletsRetail");
                });

            modelBuilder.Entity("SharedLib.WalletRetailModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserIdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("WalletTypeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.HasIndex("UserIdentityId");

                    b.HasIndex("WalletTypeId");

                    b.ToTable("WalletsRetail");
                });

            modelBuilder.Entity("SharedLib.WalletRetailTypeModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUTC");

                    b.HasIndex("LastUpdatedAtUTC");

                    b.ToTable("WalletsRetailTypes");
                });

            modelBuilder.Entity("SharedLib.WarehouseDocumentModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExternalDocumentId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUpperName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<int>("WarehouseId")
                        .HasColumnType("integer");

                    b.Property<int>("WritingOffWarehouseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryDate");

                    b.HasIndex("ExternalDocumentId");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("NormalizedUpperName");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("WritingOffWarehouseId");

                    b.ToTable("WarehouseDocuments");
                });

            modelBuilder.Entity("SharedLib.WeeklyScheduleModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContextName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("EndPart")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdatedAtUTC")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NomenclatureId")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedNameUpper")
                        .HasColumnType("text");

                    b.Property<int?>("OfferId")
                        .HasColumnType("integer");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<long>("QueueCapacity")
                        .HasColumnType("bigint");

                    b.Property<long>("SortIndex")
                        .HasColumnType("bigint");

                    b.Property<long>("StartPart")
                        .HasColumnType("bigint");

                    b.Property<int>("Weekday")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContextName");

                    b.HasIndex("IsDisabled");

                    b.HasIndex("Name");

                    b.HasIndex("NomenclatureId");

                    b.HasIndex("NormalizedNameUpper");

                    b.HasIndex("OfferId");

                    b.HasIndex("Weekday");

                    b.HasIndex("StartPart", "EndPart");

                    b.HasIndex("SortIndex", "ParentId", "ContextName")
                        .IsUnique();

                    b.ToTable("WeeklySchedules");
                });

            modelBuilder.Entity("SharedLib.BankDetailsModelDB", b =>
                {
                    b.HasOne("SharedLib.OrganizationModelDB", "Organization")
                        .WithMany("BanksDetails")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SharedLib.CalendarScheduleModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId");

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId");

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SharedLib.DeliveryDocumentRetailModelDB", b =>
                {
                    b.HasOne("SharedLib.RetailDocumentModelDB", "Order")
                        .WithMany("DeliveryDocuments")
                        .HasForeignKey("OrderId");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SharedLib.DeliveryStatusRetailDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.DeliveryDocumentRetailModelDB", "DeliveryDocument")
                        .WithMany("DeliveryStatusesLog")
                        .HasForeignKey("DeliveryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryDocument");
                });

            modelBuilder.Entity("SharedLib.OfferAvailabilityModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany("Registers")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SharedLib.OfferModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany("Offers")
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");
                });

            modelBuilder.Entity("SharedLib.OfficeOrganizationModelDB", b =>
                {
                    b.HasOne("SharedLib.OrganizationModelDB", "Organization")
                        .WithMany("Offices")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SharedLib.OrderDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.OrganizationModelDB", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SharedLib.OrganizationContractorModel", b =>
                {
                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany("Contractors")
                        .HasForeignKey("OfferId");

                    b.HasOne("SharedLib.OrganizationModelDB", "Organization")
                        .WithMany("Contractors")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SharedLib.PaymentDocumentModelDb", b =>
                {
                    b.HasOne("SharedLib.OrderDocumentModelDB", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailDeliveryLinkModelDB", b =>
                {
                    b.HasOne("SharedLib.DeliveryDocumentRetailModelDB", "DeliveryDocument")
                        .WithMany("Payments")
                        .HasForeignKey("DeliveryDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.PaymentRetailDocumentModelDB", "Payment")
                        .WithMany("DeliveriesLinks")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryDocument");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.WalletRetailModelDB", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailOrderLinkModelDB", b =>
                {
                    b.HasOne("SharedLib.RetailDocumentModelDB", "Order")
                        .WithMany("PaymentsLinks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.PaymentRetailDocumentModelDB", "Payment")
                        .WithMany("OrdersLinks")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SharedLib.PriceRuleForOfferModelDB", b =>
                {
                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany("PricesRules")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SharedLib.RecordsAttendanceModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OrganizationModelDB", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SharedLib.RowOfDeliveryRetailDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.DeliveryDocumentRetailModelDB", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SharedLib.RowOfOrderDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.TabOfficeForOrderModelDb", "OfficeOrderTab")
                        .WithMany("Rows")
                        .HasForeignKey("OfficeOrderTabId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OrderDocumentModelDB", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId");

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");

                    b.Navigation("OfficeOrderTab");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SharedLib.RowOfRetailOrderDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.RetailDocumentModelDB", "Order")
                        .WithMany("Rows")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SharedLib.RowOfWarehouseDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.WarehouseDocumentModelDB", "WarehouseDocument")
                        .WithMany("Rows")
                        .HasForeignKey("WarehouseDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");

                    b.Navigation("WarehouseDocument");
                });

            modelBuilder.Entity("SharedLib.TabOfficeForOrderModelDb", b =>
                {
                    b.HasOne("SharedLib.OfficeOrganizationModelDB", "Office")
                        .WithMany()
                        .HasForeignKey("OfficeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.OrderDocumentModelDB", "Order")
                        .WithMany("OfficesTabs")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Office");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("SharedLib.UserOrganizationModelDB", b =>
                {
                    b.HasOne("SharedLib.OrganizationModelDB", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("SharedLib.WalletConversionRetailDocumentModelDB", b =>
                {
                    b.HasOne("SharedLib.WalletRetailModelDB", "FromWallet")
                        .WithMany()
                        .HasForeignKey("FromWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.WalletRetailModelDB", "ToWallet")
                        .WithMany()
                        .HasForeignKey("ToWalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromWallet");

                    b.Navigation("ToWallet");
                });

            modelBuilder.Entity("SharedLib.WalletRetailModelDB", b =>
                {
                    b.HasOne("SharedLib.WalletRetailTypeModelDB", "WalletType")
                        .WithMany("Wallets")
                        .HasForeignKey("WalletTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WalletType");
                });

            modelBuilder.Entity("SharedLib.WeeklyScheduleModelDB", b =>
                {
                    b.HasOne("SharedLib.NomenclatureModelDB", "Nomenclature")
                        .WithMany()
                        .HasForeignKey("NomenclatureId");

                    b.HasOne("SharedLib.OfferModelDB", "Offer")
                        .WithMany()
                        .HasForeignKey("OfferId");

                    b.Navigation("Nomenclature");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("SharedLib.DeliveryDocumentRetailModelDB", b =>
                {
                    b.Navigation("DeliveryStatusesLog");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("SharedLib.NomenclatureModelDB", b =>
                {
                    b.Navigation("Offers");
                });

            modelBuilder.Entity("SharedLib.OfferModelDB", b =>
                {
                    b.Navigation("Contractors");

                    b.Navigation("PricesRules");

                    b.Navigation("Registers");
                });

            modelBuilder.Entity("SharedLib.OrderDocumentModelDB", b =>
                {
                    b.Navigation("OfficesTabs");
                });

            modelBuilder.Entity("SharedLib.OrganizationModelDB", b =>
                {
                    b.Navigation("BanksDetails");

                    b.Navigation("Contractors");

                    b.Navigation("Offices");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SharedLib.PaymentRetailDocumentModelDB", b =>
                {
                    b.Navigation("DeliveriesLinks");

                    b.Navigation("OrdersLinks");
                });

            modelBuilder.Entity("SharedLib.RetailDocumentModelDB", b =>
                {
                    b.Navigation("DeliveryDocuments");

                    b.Navigation("PaymentsLinks");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("SharedLib.TabOfficeForOrderModelDb", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("SharedLib.WalletRetailTypeModelDB", b =>
                {
                    b.Navigation("Wallets");
                });

            modelBuilder.Entity("SharedLib.WarehouseDocumentModelDB", b =>
                {
                    b.Navigation("Rows");
                });
#pragma warning restore 612, 618
        }
    }
}
