// <auto-generated />
using System;
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbPostgreLib.Migrations.Storage
{
    [DbContext(typeof(StorageContext))]
    [Migration("20251112074111_StorageContext001")]
    partial class StorageContext001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLib.AccessFileRuleModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessRuleType")
                        .HasColumnType("integer");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StoreFileId");

                    b.ToTable("RulesFilesAccess");
                });

            modelBuilder.Entity("SharedLib.CellTableExcelIndexFileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ColNum")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<long>("RowNum")
                        .HasColumnType("bigint");

                    b.Property<int>("SheetExcelFileId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("SheetExcelFileId");

                    b.HasIndex("StoreFileId");

                    b.ToTable("DataTablesExcelIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.CellTableWordIndexFileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ColNum")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<long>("RowNum")
                        .HasColumnType("bigint");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.Property<int>("TableWordFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("StoreFileId");

                    b.HasIndex("TableWordFileId");

                    b.ToTable("DataTablesWordIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.ParagraphWordIndexFileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("SortIndex");

                    b.HasIndex("StoreFileId");

                    b.ToTable("ParagraphsWordIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.SheetExcelIndexFileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortIndex");

                    b.HasIndex("StoreFileId");

                    b.HasIndex("Title");

                    b.ToTable("SheetsExcelIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.StorageCloudParameterModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OwnerPrimaryKey")
                        .HasColumnType("integer");

                    b.Property<string>("PrefixPropertyName")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .HasColumnType("text");

                    b.Property<string>("SerializedDataJson")
                        .HasColumnType("text");

                    b.Property<string>("TypeName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("TypeName");

                    b.HasIndex("ApplicationName", "PropertyName");

                    b.HasIndex("PrefixPropertyName", "OwnerPrimaryKey");

                    b.ToTable("CloudProperties");
                });

            modelBuilder.Entity("SharedLib.StorageFileModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("text");

                    b.Property<string>("AuthorIdentityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FileLength")
                        .HasColumnType("bigint");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedFileNameUpper")
                        .HasColumnType("text");

                    b.Property<int?>("OwnerPrimaryKey")
                        .HasColumnType("integer");

                    b.Property<string>("PointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PrefixPropertyName")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .HasColumnType("text");

                    b.Property<string>("ReferrerMain")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorIdentityId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FileName");

                    b.HasIndex("NormalizedFileNameUpper");

                    b.HasIndex("PointId");

                    b.HasIndex("ReferrerMain");

                    b.HasIndex("ApplicationName", "PropertyName");

                    b.HasIndex("PrefixPropertyName", "OwnerPrimaryKey");

                    b.ToTable("CloudFiles");
                });

            modelBuilder.Entity("SharedLib.TableWordIndexFileModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortIndex");

                    b.HasIndex("StoreFileId");

                    b.ToTable("TablesWordIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.TagModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedTagNameUpper")
                        .HasColumnType("text");

                    b.Property<int?>("OwnerPrimaryKey")
                        .HasColumnType("integer");

                    b.Property<string>("PrefixPropertyName")
                        .HasColumnType("text");

                    b.Property<string>("PropertyName")
                        .HasColumnType("text");

                    b.Property<string>("TagName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NormalizedTagNameUpper");

                    b.HasIndex("ApplicationName", "PropertyName");

                    b.HasIndex("PrefixPropertyName", "OwnerPrimaryKey");

                    b.HasIndex(new[] { "NormalizedTagNameUpper", "OwnerPrimaryKey", "ApplicationName" }, "IX_TagNameOwnerKeyUnique")
                        .IsUnique();

                    b.ToTable("CloudTags");
                });

            modelBuilder.Entity("SharedLib.AccessFileRuleModelDB", b =>
                {
                    b.HasOne("SharedLib.StorageFileModelDB", "StoreFile")
                        .WithMany("AccessRules")
                        .HasForeignKey("StoreFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreFile");
                });

            modelBuilder.Entity("SharedLib.CellTableExcelIndexFileModel", b =>
                {
                    b.HasOne("SharedLib.SheetExcelIndexFileModel", "SheetExcelFile")
                        .WithMany()
                        .HasForeignKey("SheetExcelFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.StorageFileModelDB", "StoreFile")
                        .WithMany()
                        .HasForeignKey("StoreFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheetExcelFile");

                    b.Navigation("StoreFile");
                });

            modelBuilder.Entity("SharedLib.CellTableWordIndexFileModel", b =>
                {
                    b.HasOne("SharedLib.StorageFileModelDB", "StoreFile")
                        .WithMany()
                        .HasForeignKey("StoreFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SharedLib.TableWordIndexFileModel", "TableWordFile")
                        .WithMany()
                        .HasForeignKey("TableWordFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreFile");

                    b.Navigation("TableWordFile");
                });

            modelBuilder.Entity("SharedLib.ParagraphWordIndexFileModel", b =>
                {
                    b.HasOne("SharedLib.StorageFileModelDB", "StoreFile")
                        .WithMany()
                        .HasForeignKey("StoreFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreFile");
                });

            modelBuilder.Entity("SharedLib.SheetExcelIndexFileModel", b =>
                {
                    b.HasOne("SharedLib.StorageFileModelDB", "StoreFile")
                        .WithMany()
                        .HasForeignKey("StoreFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreFile");
                });

            modelBuilder.Entity("SharedLib.TableWordIndexFileModel", b =>
                {
                    b.HasOne("SharedLib.StorageFileModelDB", "StoreFile")
                        .WithMany()
                        .HasForeignKey("StoreFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StoreFile");
                });

            modelBuilder.Entity("SharedLib.StorageFileModelDB", b =>
                {
                    b.Navigation("AccessRules");
                });
#pragma warning restore 612, 618
        }
    }
}
