// <auto-generated />
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DbPostgreLib.Migrations.FilesIndexing
{
    [DbContext(typeof(FilesIndexingContext))]
    [Migration("20251116142156_FilesIndexingContext001")]
    partial class FilesIndexingContext001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SharedLib.CellTableExcelIndexFileModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ColNum")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("RowNum")
                        .HasColumnType("bigint");

                    b.Property<int>("SheetExcelFileId")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("SheetExcelFileId");

                    b.HasIndex("StoreFileId");

                    b.ToTable("DataTablesExcelIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.CellTableWordIndexFileModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ColNum")
                        .HasColumnType("bigint");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParagraphId")
                        .HasColumnType("text");

                    b.Property<long>("RowNum")
                        .HasColumnType("bigint");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.Property<int>("TableWordFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("StoreFileId");

                    b.HasIndex("TableWordFileId");

                    b.ToTable("DataTablesWordIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.ParagraphWordIndexFileModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .HasColumnType("text");

                    b.Property<string>("ParagraphId")
                        .HasColumnType("text");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Data");

                    b.HasIndex("SortIndex");

                    b.HasIndex("StoreFileId");

                    b.ToTable("ParagraphsWordIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.SheetExcelIndexFileModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SortIndex");

                    b.HasIndex("StoreFileId");

                    b.HasIndex("Title");

                    b.ToTable("SheetsExcelIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.TableWordIndexFileModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("StoreFileId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SortIndex");

                    b.HasIndex("StoreFileId");

                    b.ToTable("TablesWordIndexesFiles");
                });

            modelBuilder.Entity("SharedLib.CellTableExcelIndexFileModelDB", b =>
                {
                    b.HasOne("SharedLib.SheetExcelIndexFileModelDB", "SheetExcelFile")
                        .WithMany("Cells")
                        .HasForeignKey("SheetExcelFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SheetExcelFile");
                });

            modelBuilder.Entity("SharedLib.CellTableWordIndexFileModelDB", b =>
                {
                    b.HasOne("SharedLib.TableWordIndexFileModelDB", "TableWordFile")
                        .WithMany("Data")
                        .HasForeignKey("TableWordFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableWordFile");
                });

            modelBuilder.Entity("SharedLib.SheetExcelIndexFileModelDB", b =>
                {
                    b.Navigation("Cells");
                });

            modelBuilder.Entity("SharedLib.TableWordIndexFileModelDB", b =>
                {
                    b.Navigation("Data");
                });
#pragma warning restore 612, 618
        }
    }
}
